version: '3.8'
services:
  project-db:
    image: "postgres:latest"
    environment:
      - 'POSTGRES_DB=project_db'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=123'
    ports:
      - '5432:5432'
  app:
    build: .
    ports:
      - '8000:8000'