version: '3.8'
services:
  project-db:
    image: "postgres:latest"
    env_file:
      - ./creds.env
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d testDB"]
      interval: 10s
      retries: 5

  app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      project-db:
        condition: service_healthy